name: 🏗️ Build
on: push

jobs:
  build:
    name: 🏗️ Build
    uses: acidicoala/KoalaBox/.github/workflows/build.yml@7e7e1121acd8591fad3bfa2895fd1b9c1bf57afb
    with:
      #language=json
      module: '[ "SmokeAPI" ] '

      #language=json
      os: '[ "Windows", "Linux" ]'

      #language=json
      bitness: '[ 32, 64 ]'
