name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@7652ece92dc3461e07ac099344ec5fc4a472462a
    permissions:
      contents: write
    with:
      arch: '[ 32, 64 ]'
      config: Release
      modules: '[ "SmokeAPI" ]'
      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
        res/SmokeAPI.config.json
