name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@aad92bf86387baa790105c40109d0d6fbb0bb629
    permissions:
      contents: write
    with:
      arch: '[ 32, 64 ]'
      config: Release
      modules: '[ "SmokeAPI" ]'
      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
        res/SmokeAPI.config.json
        res/README.txt
