name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@f97e4e4fcef5374ac81c1584eff74f595527e15a
    permissions:
      contents: write
    with:
      arch: '[ 32, 64 ]'
      config: Release
      modules: '[ "SmokeAPI" ]'
      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
        res/SmokeAPI.config.json
        res/README.txt
